---
title: "Playoffs 2 Data"
author: "Praveen Puviindran"
date: "2024-04-02"
output: pdf_document
---

```{r setup, include=FALSE}
library(readr)

nba_api <- read_csv("/Users/praveenpuviindran/Downloads/2019to2024nbagamestats.csv")

head(nba_api)
```

```{r}
# This script scrapes top-level NBA schedule and results from basketball-reference.com.
# User can set year and list of months to determine the window of games to scrape.
# At the end of the script, I reconstruct the conference standings based on W-L
# percentage.

library(rvest)
library(lubridate)
library(tidyverse)

########
# PARAMETERS
########
year <- "2024"
monthList <- c("october", "november", "december", "january", "february", 
               "march")
playoff_startDate <- ymd("2024-04-20")
outputfile <- "NBA-2024_game_data.rds"

########
# SCRIPT FOR SCRAPING DATA STARTS HERE
########
df <- data.frame()
for (month in monthList) {
  # get webpage
  url <- paste0("https://www.basketball-reference.com/leagues/NBA_", year, 
                "_games-", month, ".html")
  webpage <- read_html(url)
  
  # get column names
  col_names <- webpage %>% 
    html_nodes("table#schedule > thead > tr > th") %>% 
    html_attr("data-stat")    
  col_names <- c("game_id", col_names)
  
  # extract dates column
  # note that in april, there is a break in the table which just says 
  # "Playoffs". this messes with the data merging later, so we get rid of it
  dates <- webpage %>% 
    html_nodes("table#schedule > tbody > tr > th") %>% 
    html_text()
  dates <- dates[dates != "Playoffs"]
  
  # extract game id
  # we need to remove the NA that is due to the "Playoffs" row in april
  game_id <- webpage %>% 
    html_nodes("table#schedule > tbody > tr > th") %>%
    html_attr("csk")
  game_id <- game_id[!is.na(game_id)]
  
  # extract all columns (except date)
  data <- webpage %>% 
    html_nodes("table#schedule > tbody > tr > td") %>% 
    html_text() %>%
    matrix(ncol = length(col_names) - 2, byrow = TRUE)
  
  # combine game IDs, dates and columns in dataframe for this month, add col names
  month_df <- as.data.frame(cbind(game_id, dates, data), stringsAsFactors = FALSE)
  names(month_df) <- col_names
  
  # add to overall dataframe
  df <- rbind(df, month_df)
}

# change columns to the correct types
df$visitor_pts <- as.numeric(df$visitor_pts)
df$home_pts    <- as.numeric(df$home_pts)
df$attendance  <- as.numeric(gsub(",", "", df$attendance))
df$date_game   <- mdy(df$date_game)

# add column to indicate if regular season or playoff
df$game_type <- with(df, ifelse(date_game >= playoff_startDate, 
                                "Playoff", "Regular"))

# drop boxscore column
df$box_score_text <- NULL

# save to file
saveRDS(df, outputfile)

########
# SCRIPT FOR RANKING TABLE STARTS HERE
########

# get winner and loser of each game
df$winner <- with(df, ifelse(visitor_pts > home_pts, 
                             visitor_team_name, home_team_name))
df$loser <- with(df, ifelse(visitor_pts < home_pts, 
                            visitor_team_name, home_team_name))

# build up standings table for regular season
regular_df <- subset(df, game_type == "Regular")
regular_df <- na.omit(regular_df)
teams <- sort(unique(regular_df$visitor_team_name))
standings <- data.frame(team = teams, stringsAsFactors = FALSE)

# conference & division information: manually input
standings$conf <- c("East", "East", "East", "East", "East",
                    "East", "West", "West", "East", "West",
                    "West", "East", "West", "West", "West",
                    "East", "East", "West", "West", "East",
                    "West", "East", "East", "West", "West",
                    "West", "West", "East", "West", "East")
standings$div <- c("Southeast", "Atlantic", "Atlantic", "Southeast", "Central",
                   "Central", "Southwest", "Northwest", "Central", "Pacific",
                   "Southwest", "Central", "Pacific", "Pacific", "Southwest",
                   "Southeast", "Central", "Northwest", "Southwest", "Atlantic",
                   "Northwest", "Southeast", "Atlantic", "Pacific", "Northwest",
                   "Pacific", "Southwest", "Atlantic", "Northwest", "Southeast")

# populate W-L column, W pct
standings$win <- 0; standings$loss <- 0
for (i in 1:nrow(standings)) {
  standings$win[i]  <- sum(regular_df$winner == standings$team[i])
  standings$loss[i] <- sum(regular_df$loser  == standings$team[i])
}
standings$wl_pct <- with(standings, win / (win + loss))

# Eastern conference standings
east_standings <- subset(standings, conf == "East")
east_standings[with(east_standings, order(-wl_pct, team)), 
               c("team", "win", "loss")]

# Western conference standings
west_standings <- subset(standings, conf == "West")
west_standings[with(west_standings, order(-wl_pct, team)), 
               c("team", "win", "loss")]
```

```{r}
regular_df$home_prior_form <- nrow(regular_df)*NA

regular_df$visitor_prior_form <- nrow(regular_df)*NA



```

```{r}

for (i in 1:length(unique(regular_df$visitor_team_name))){
  

  adapted_df <- regular_df |> 
    filter(visitor_team_name == unique(regular_df$visitor_team_name)[i] | home_team_name == unique(regular_df$visitor_team_name)[i])
  

for (j in 1:(nrow(adapted_df) - 1)) 
  {

adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]


if(adapted_df$visitor_team_name[j] == unique(regular_df$visitor_team_name)[i]){
#Are selected team away?
  
      if(is.na(adapted_df$visitor_prior_form[j])){
        #Is var column empty?
          if(adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
            if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            
            adapted_df$visitor_prior_form[j+1] <- "W"
            }
            else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- "W"

            }
        }
        if(adapted_df$loser[j]  == unique(regular_df$visitor_team_name)[i]){
          #Did selected team lose?
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            
            adapted_df$visitor_prior_form[j+1] <- "L"
            }
            else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- "L"

            }
        }
      }
      else if(nchar(adapted_df$visitor_prior_form[j]) < 9){
        
        if(adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
          
          adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$visitor_prior_form[j], "W")
       
          }
          else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$visitor_prior_form[j], "W")
          }
        }
        else if(adapted_df$loser[j] == unique(regular_df$visitor_team_name)[i]){
          #Team lost
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
          #Is team away next?
          adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$visitor_prior_form[j], "L")
          
          }
          else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i])
            #Is team at home next?
            {
            adapted_df$home_prior_form[j+1] <- paste(adapted_df$visitor_prior_form[j], "L")
          }
        }
        }
        
 else if (nchar(adapted_df$visitor_prior_form[j]) >= 9){
        if (adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
          #Did team win?
          
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(substr(adapted_df$visitor_prior_form[j], 3, 9), "W")
          }
          
          if(adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(substr(adapted_df$visitor_prior_form[j], 3, 9), "W")
          }
          
            
            }
        else if (adapted_df$loser[j] == unique(regular_df$visitor_team_name)[i]){
          
          
           if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(substr(adapted_df$visitor_prior_form[j], 3, 9), "L")
          }
          
          if(adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(substr(adapted_df$visitor_prior_form[j], 3, 9), "L")
          }
        }
      }
}





if(adapted_df$home_team_name[j] == unique(regular_df$visitor_team_name)[i]){
  
      if(is.na(adapted_df$home_prior_form[j])){
          if(adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
            if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            
            adapted_df$visitor_prior_form[j+1] <- "W"
            }
            else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- "W"

            }
          }
        if(adapted_df$loser[j]  == unique(regular_df$visitor_team_name)[i]){
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            
            adapted_df$visitor_prior_form[j+1] <- "L"
            }
            else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- "L"

            }
        }
      }
      else if(nchar(adapted_df$home_prior_form[j]) < 9){
        
        if(adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
          
          adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$home_prior_form[j], "W")
       
          }
          else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(adapted_df$home_prior_form[j], "W")
          }
        }
        else if(adapted_df$loser[j] == unique(regular_df$visitor_team_name)[i]){
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
          
          adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$home_prior_form[j], "L")
       
          }
          else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(adapted_df$home_prior_form[j], "L")
          }
        }
        }
        
 else if (nchar(adapted_df$home_prior_form[j]) >= 9){
        if (adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
          
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(substr(adapted_df$home_prior_form[j], 3, 9), "W")
          }
          
          if(adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(substr(adapted_df$home_prior_form[j], 3, 9), "W")
          }
          
            
            }
        else if (adapted_df$loser[j] == unique(regular_df$visitor_team_name)[i]){
          
          
           if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(substr(adapted_df$home_prior_form[j], 3, 9), "L")
          }
          
          if(adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(substr(adapted_df$home_prior_form[j], 3, 9), "L")
          }
        }
      }
    }

    
    regular_df <- regular_df |> 
      rbind(adapted_df[j,])
    
}
}
#Add condition: away next game vs. home next game and then add it to column
    

```


```{r}

final_df <- na.omit(regular_df)

head(final_df)
```


```{r}
str_replace_all(nba_api$TEAM_NAME, "LA Clippers", "Los Angeles Clippers")


home2023_24 <- nba_api |> 
  right_join(final_df, join_by(GAME_DATE == date_game, TEAM_NAME == home_team_name)) |> 
    rename(opposition = visitor_team_name) 


away2023_24 <- nba_api |> 
  right_join(final_df, join_by(GAME_DATE == date_game, TEAM_NAME == visitor_team_name)) |> 
  rename(opposition = home_team_name) |> 
  relocate(32, .before = 31)

names(home2023_24) == names(away2023_24)

combined <- rbind(home2023_24, away2023_24)
combined
```

```{r}
#Sample code to find monthly averages




combined |> 
  filter(format(GAME_DATE, "%m") == "03") |> 
  group_by(TEAM_NAME) 
```

```{r}
# Load necessary libraries
library(dplyr)
library(readr)

# Load the dataset
game_stats <- nba_api

# Inspect the dataset
head(game_stats)

```

```{r}
# Assuming 'game_stats' includes columns for team, opponent team, game date, and necessary stats

# Calculate Team Shooting Percentage
game_stats <- game_stats %>%
  mutate(Shooting_Percentage = FGM / FGA) %>%
  group_by(TEAM_NAME) %>%
  mutate(Avg_Shooting_Percentage = mean(Shooting_Percentage, na.rm = TRUE))

# Calculate Average OREB per Game
game_stats <- game_stats %>%
  group_by(TEAM_NAME) %>%
  mutate(Avg_OREB = mean(OREB, na.rm = TRUE))

# Opposition Team's Historic DREB (this would require a bit more complex logic to calculate historically for each game)
# For simplification, let's calculate the average DREB for the season
game_stats <- game_stats %>%
  group_by(MATCHUP) %>%
  mutate(Opponent_Avg_DREB = mean(DREB, na.rm = TRUE))

# Since calculating the tendencies of different players on teams might be too specific and complex for this example,
# we'll proceed with the above features for the model.
game_stats
```

```{r}
# Splitting the data into training and testing sets (simplified example)
set.seed(123)
training_indices <- sample(seq_len(nrow(game_stats)), size = floor(0.8 * nrow(game_stats)))
training_data <- game_stats[training_indices, ]
testing_data <- game_stats[-training_indices, ]

# Build the model
model <- lm(OREB ~ Avg_Shooting_Percentage + Avg_OREB + Opponent_Avg_DREB, data = training_data)

# Summary of the model
summary(model)

# Predict and evaluate
predictions <- predict(model, newdata = testing_data)
mae <- mean(abs(predictions - testing_data$OREB))
print(paste("Mean Absolute Error:", mae))

```

```{r}

```

