---
title: "Playoff2"
output: html_document
date: "2024-04-02"
---
```{r}
library(readr)


nba_api <- read_csv("/Users/ethantur/Documents/STOR538/2019to2024nbagamestats.csv") 

head(nba_api)
```

```{r}
# This script scrapes top-level NBA schedule and results from basketball-reference.com.
# User can set year and list of months to determine the window of games to scrape.
# At the end of the script, I reconstruct the conference standings based on W-L
# percentage.

library(rvest)
library(lubridate)
library(tidyverse)

########
# PARAMETERS
########
year <- "2024"
monthList <- c("october", "november", "december", "january", "february", 
               "march", "april")
playoff_startDate <- ymd("2024-04-20")
outputfile <- "NBA-2024_game_data.rds"

########
# SCRIPT FOR SCRAPING DATA STARTS HERE
########
df <- data.frame()
for (month in monthList) {
  # get webpage
  url <- paste0("https://www.basketball-reference.com/leagues/NBA_", year, 
                "_games-", month, ".html")
  webpage <- read_html(url)
  
  # get column names
  col_names <- webpage %>% 
    html_nodes("table#schedule > thead > tr > th") %>% 
    html_attr("data-stat")    
  col_names <- c("game_id", col_names)
  
  # extract dates column
  # note that in april, there is a break in the table which just says 
  # "Playoffs". this messes with the data merging later, so we get rid of it
  dates <- webpage %>% 
    html_nodes("table#schedule > tbody > tr > th") %>% 
    html_text()
  dates <- dates[dates != "Playoffs"]
  
  # extract game id
  # we need to remove the NA that is due to the "Playoffs" row in april
  game_id <- webpage %>% 
    html_nodes("table#schedule > tbody > tr > th") %>%
    html_attr("csk")
  game_id <- game_id[!is.na(game_id)]
  
  # extract all columns (except date)
  data <- webpage %>% 
    html_nodes("table#schedule > tbody > tr > td") %>% 
    html_text() %>%
    matrix(ncol = length(col_names) - 2, byrow = TRUE)
  
  # combine game IDs, dates and columns in dataframe for this month, add col names
  month_df <- as.data.frame(cbind(game_id, dates, data), stringsAsFactors = FALSE)
  names(month_df) <- col_names
  
  # add to overall dataframe
  df <- rbind(df, month_df)
}

# change columns to the correct types
df$visitor_pts <- as.numeric(df$visitor_pts)
df$home_pts    <- as.numeric(df$home_pts)
df$attendance  <- as.numeric(gsub(",", "", df$attendance))
df$date_game   <- mdy(df$date_game)

# add column to indicate if regular season or playoff
df$game_type <- with(df, ifelse(date_game >= playoff_startDate, 
                                "Playoff", "Regular"))

# drop boxscore column
df$box_score_text <- NULL

# save to file
saveRDS(df, outputfile)

########
# SCRIPT FOR RANKING TABLE STARTS HERE
########

# get winner and loser of each game
df$winner <- with(df, ifelse(visitor_pts > home_pts, 
                             visitor_team_name, home_team_name))
df$loser <- with(df, ifelse(visitor_pts < home_pts, 
                            visitor_team_name, home_team_name))

# build up standings table for regular season
regular_df <- subset(df, game_type == "Regular")
regular_df <- na.omit(regular_df)
teams <- sort(unique(regular_df$visitor_team_name))
standings <- data.frame(team = teams, stringsAsFactors = FALSE)

# conference & division information: manually input
standings$conf <- c("East", "East", "East", "East", "East",
                    "East", "West", "West", "East", "West",
                    "West", "East", "West", "West", "West",
                    "East", "East", "West", "West", "East",
                    "West", "East", "East", "West", "West",
                    "West", "West", "East", "West", "East")
standings$div <- c("Southeast", "Atlantic", "Atlantic", "Southeast", "Central",
                   "Central", "Southwest", "Northwest", "Central", "Pacific",
                   "Southwest", "Central", "Pacific", "Pacific", "Southwest",
                   "Southeast", "Central", "Northwest", "Southwest", "Atlantic",
                   "Northwest", "Southeast", "Atlantic", "Pacific", "Northwest",
                   "Pacific", "Southwest", "Atlantic", "Northwest", "Southeast")

# populate W-L column, W pct
standings$win <- 0; standings$loss <- 0
for (i in 1:nrow(standings)) {
  standings$win[i]  <- sum(regular_df$winner == standings$team[i])
  standings$loss[i] <- sum(regular_df$loser  == standings$team[i])
}
standings$wl_pct <- with(standings, win / (win + loss))

# Eastern conference standings
east_standings <- subset(standings, conf == "East")
east_standings[with(east_standings, order(-wl_pct, team)), 
               c("team", "win", "loss")]

# Western conference standings
west_standings <- subset(standings, conf == "West")
west_standings[with(west_standings, order(-wl_pct, team)), 
               c("team", "win", "loss")]
```

```{r}
regular_df$home_prior_form <- nrow(regular_df)*NA

regular_df$visitor_prior_form <- nrow(regular_df)*NA



```


```{r}
for (i in 1:length(unique(regular_df$visitor_team_name))){
  

  adapted_df <- regular_df |> 
    filter(visitor_team_name == unique(regular_df$visitor_team_name)[i] | home_team_name == unique(regular_df$visitor_team_name)[i])
  

for (j in 1:(nrow(adapted_df) - 1)) 
  {

adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]


if(adapted_df$visitor_team_name[j] == unique(regular_df$visitor_team_name)[i]){
#Are selected team away?
  
      if(is.na(adapted_df$visitor_prior_form[j])){
        #Is var column empty?
          if(adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
            if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            
            adapted_df$visitor_prior_form[j+1] <- "W"
            }
            else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- "W"

            }
        }
        if(adapted_df$loser[j]  == unique(regular_df$visitor_team_name)[i]){
          #Did selected team lose?
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            
            adapted_df$visitor_prior_form[j+1] <- "L"
            }
            else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- "L"

            }
        }
      }
      else if(nchar(adapted_df$visitor_prior_form[j]) < 9){
        
        if(adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
          
          adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$visitor_prior_form[j], "W")
       
          }
          else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$visitor_prior_form[j], "W")
          }
        }
        else if(adapted_df$loser[j] == unique(regular_df$visitor_team_name)[i]){
          #Team lost
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
          #Is team away next?
          adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$visitor_prior_form[j], "L")
          
          }
          else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i])
            #Is team at home next?
            {
            adapted_df$home_prior_form[j+1] <- paste(adapted_df$visitor_prior_form[j], "L")
          }
        }
        }
        
 else if (nchar(adapted_df$visitor_prior_form[j]) >= 9){
        if (adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
          #Did team win?
          
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(substr(adapted_df$visitor_prior_form[j], 3, 9), "W")
          }
          
          if(adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(substr(adapted_df$visitor_prior_form[j], 3, 9), "W")
          }
          
            
            }
        else if (adapted_df$loser[j] == unique(regular_df$visitor_team_name)[i]){
          
          
           if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(substr(adapted_df$visitor_prior_form[j], 3, 9), "L")
          }
          
          if(adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(substr(adapted_df$visitor_prior_form[j], 3, 9), "L")
          }
        }
      }
}





if(adapted_df$home_team_name[j] == unique(regular_df$visitor_team_name)[i]){
  
      if(is.na(adapted_df$home_prior_form[j])){
          if(adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
            if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            
            adapted_df$visitor_prior_form[j+1] <- "W"
            }
            else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- "W"

            }
          }
        if(adapted_df$loser[j]  == unique(regular_df$visitor_team_name)[i]){
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            
            adapted_df$visitor_prior_form[j+1] <- "L"
            }
            else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- "L"

            }
        }
      }
      else if(nchar(adapted_df$home_prior_form[j]) < 9){
        
        if(adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
          
          adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$home_prior_form[j], "W")
       
          }
          else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(adapted_df$home_prior_form[j], "W")
          }
        }
        else if(adapted_df$loser[j] == unique(regular_df$visitor_team_name)[i]){
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
          
          adapted_df$visitor_prior_form[j+1] <- paste(adapted_df$home_prior_form[j], "L")
       
          }
          else if (adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(adapted_df$home_prior_form[j], "L")
          }
        }
        }
        
 else if (nchar(adapted_df$home_prior_form[j]) >= 9){
        if (adapted_df$winner[j] == unique(regular_df$visitor_team_name)[i]){
          
          if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(substr(adapted_df$home_prior_form[j], 3, 9), "W")
          }
          
          if(adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(substr(adapted_df$home_prior_form[j], 3, 9), "W")
          }
          
            
            }
        else if (adapted_df$loser[j] == unique(regular_df$visitor_team_name)[i]){
          
          
           if(adapted_df$visitor_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$visitor_prior_form[j+1] <- paste(substr(adapted_df$home_prior_form[j], 3, 9), "L")
          }
          
          if(adapted_df$home_team_name[j+1] == unique(regular_df$visitor_team_name)[i]){
            adapted_df$home_prior_form[j+1] <- paste(substr(adapted_df$home_prior_form[j], 3, 9), "L")
          }
        }
      }
    }

    
    regular_df <- regular_df |> 
      rbind(adapted_df[j,])
    
}
}
#Add condition: away next game vs. home next game and then add it to column
    

```



```{r}

final_df <- na.omit(regular_df)

head(final_df)


```


```{r}
nba_api$TEAM_NAME = str_replace_all(nba_api$TEAM_NAME, "LA Clippers", "Los Angeles Clippers")


home2023_24 <- nba_api |> 
  right_join(final_df, join_by(GAME_DATE == date_game, TEAM_NAME == home_team_name)) |> 
    rename(opposition = visitor_team_name) 


away2023_24 <- nba_api |> 
  right_join(final_df, join_by(GAME_DATE == date_game, TEAM_NAME == visitor_team_name)) |> 
  rename(opposition = home_team_name) |> 
  relocate(32, .before = 31)

#names(home2023_24) == names(away2023_24)

combined <- rbind(home2023_24, away2023_24)

```

```{r}
#Sample code to find monthly averages



combined |> 
  filter(format(GAME_DATE, "%m") == "02") |> 
  group_by(TEAM_NAME) |> 
  summarise(mean(OREB))

combined |> 
  filter(format(GAME_DATE, "%m") == "02") |> 
    group_by(opposition) |> 
  summarise(mean(DREB))
```

```{r}
# Assuming 'game_stats' includes columns for team, opponent team, game date, and necessary stats
game_stats <- combined 
# Calculate Team Shooting Percentage
game_stats <- game_stats %>%
  mutate(Shooting_Percentage = FGM / FGA) %>%
  group_by(TEAM_NAME) %>%
  mutate(Avg_Shooting_Percentage = mean(Shooting_Percentage, na.rm = TRUE))

# Calculate Average OREB per Game
game_stats <- game_stats %>%
  group_by(TEAM_NAME) %>%
  mutate(Avg_OREB = mean(OREB, na.rm = TRUE))

# Opposition Team's Historic DREB (this would require a bit more complex logic to calculate historically for each game)
# For simplification, let's calculate the average DREB for the season
game_stats <- game_stats %>%
  group_by(MATCHUP) %>%
  mutate(Opponent_Avg_DREB = mean(DREB, na.rm = TRUE))

# Since calculating the tendencies of different players on teams might be too specific and complex for this example,
# we'll proceed with the above features for the model.
game_stats
```

```{r}
# Splitting the data into training and testing sets (simplified example)
set.seed(123)
training_indices <- sample(seq_len(nrow(game_stats)), size = floor(0.8 * nrow(game_stats)))
training_data <- game_stats[training_indices, ]
testing_data <- game_stats[-training_indices, ]

# Build the model
model <- lm(OREB ~ Avg_Shooting_Percentage + Avg_OREB + Opponent_Avg_DREB, data = training_data)

# Summary of the model
summary(model)

# Predict and evaluate
predictions <- predict(model, newdata = testing_data)
mae <- mean(abs(predictions - testing_data$OREB))
print(paste("Mean Absolute Error:", mae))

```


```{r}
game_stats <- game_stats %>%
   mutate(HomeTeam = ifelse(grepl("@", MATCHUP), 0, 1)) %>%
  group_by(TEAM_NAME) %>%
  mutate(average_treb = mean(REB, na.rm = TRUE)) %>%
  mutate(average_ast = mean(AST, na.rm = TRUE))
 

```



```{r}
game_stats <- game_stats %>%
  mutate(
    # Shooting Efficiency: Points per Field Goal Attempt and Free Throw Attempt
    SE = PTS / (FGA + 0.44 * FTA), # The 0.44 factor adjusts for and-one's, technical foul shots, and three-shot fouls
    
    # Defensive Pressure: Combining Steals and Blocks
    DP = (STL + BLK) / MIN, # Normalized by minutes played
    
    # Opponent Scoring Efficiency needs opponent stats; for simplicity, let's assume it's calculated
    # This step is skipped here due to its complexity, as it would require merging team stats on each game
    
    # Home Advantage as a binary variable
    Home = ifelse(grepl("vs", MATCHUP), 1, 0)
  )

# Prepare for modeling: Remove any rows with NAs created during feature engineering
game_stats <- na.omit(game_stats)
game_stats$Pace = (game_stats$FGA + 0.44 * game_stats$FTA + game_stats$TOV + game_stats$OREB) / game_stats$MIN

game_stats
```

```{r}
# Assuming 'game_stats' is your data frame and already includes SE and DP

# Calculate min and max for Shooting Efficiency (SE)
min_SE <- min(game_stats$SE, na.rm = TRUE)
max_SE <- max(game_stats$SE, na.rm = TRUE)

# Calculate min and max for Defensive Pressure (DP)
min_DP <- min(game_stats$DP, na.rm = TRUE)
max_DP <- max(game_stats$DP, na.rm = TRUE)

# Print the results
print(paste("Min SE:", min_SE, "- Max SE:", max_SE))
print(paste("Min DP:", min_DP, "- Max DP:", max_DP))
```

```{r}
game_stats$point_difference <- game_stats$home_pts - game_stats$visitor_pts 
```

```{r}
game_stats <- game_stats %>%
  mutate(
    # Shooting Efficiency: Points per Field Goal Attempt and Free Throw Attempt
    SE = PTS / (FGA + 0.44 * FTA), # The 0.44 factor adjusts for and-one's, technical foul shots, and three-shot fouls
    
    # Defensive Pressure: Combining Steals and Blocks
    DP = (STL + BLK) / MIN, # Normalized by minutes played
    
    # Home Advantage as a binary variable
    Home = ifelse(grepl("vs", MATCHUP), 1, 0)
  )

# Prepare for modeling: Remove any rows with NAs created during feature engineering
game_stats <- na.omit(game_stats)
game_stats$Pace = (game_stats$FGA + 0.44 * game_stats$FTA + game_stats$TOV + game_stats$OREB) / game_stats$MIN
# Estimate possessions based on available stats
game_stats$Possessions <- with(game_stats, 0.96 * (FGA + 0.44 * FTA - OREB + TOV))

# Calculate ORtg and DRtg
game_stats <- game_stats %>%
  mutate(ORtg = 100 * PTS / Possessions,
         DRtg = 100 * ifelse(Home == 1, visitor_pts, home_pts) / Possessions)

game_stats
```

```{r}
# Assuming 'home_prior_form' and 'visitor_prior_form' are encoded in a win-loss format (e.g., "WWL")
game_stats$HomeFormScore <- stringr::str_count(game_stats$home_prior_form, "W") - stringr::str_count(game_stats$home_prior_form, "L")
game_stats$VisitorFormScore <- stringr::str_count(game_stats$visitor_prior_form, "W") - stringr::str_count(game_stats$visitor_prior_form, "L")

game_stats$FormDiff <- game_stats$HomeFormScore - game_stats$VisitorFormScore
game_stats <- game_stats %>%
  select(-game_start_time, -home_prior_form, -visitor_prior_form) %>%
  na.omit()

```



```{r}
spreadmodel <- lm(point_difference ~  Pace + ORtg + DRtg, data= game_stats)
summary(spreadmodel)
```

```{r}
head(game_stats)
```


```{r}
OREBmodel <- lm(OREB ~ sqrt(DREB) + average_treb + Possessions + Avg_Shooting_Percentage + average_treb + FTA + FGA + FG_PCT + FGM + TEAM_NAME + opposition + Pace + FTA*FGA + FGA*FGM, data = game_stats)
summary(OREBmodel)
```


```{r}
set.seed(123)
training_indices <- sample(seq_len(nrow(game_stats)), size = floor(0.8 * nrow(game_stats)))
training_data <- game_stats[training_indices, ]
testing_data <- game_stats[-training_indices, ]
```

```{r}
predict(OREBmodel, data = testing_data)
```


```{r}
game_stats$TotalPts = game_stats$home_pts + game_stats$visitor_pts
TotalPointsModel <- lm(TotalPts ~  Pace + Possessions +  FGA + FTA  + FG3M + FGA*FTA + FGA*FGM +FGM + ORtg + DRtg, data = game_stats)
summary(TotalPointsModel)
```





































Source: Pro Sports Transactions

https://www.prosportstransactions.com/basketball/Search/SearchResults.php?Player=&Team=&BeginDate=2023-10-01&EndDate=2024-04-01&InjuriesChkBx=yes&Submit=Search&start=550

```{r}
library(rvest)
library(lubridate)
library(tidyverse)


```

```{r}
injuries <- data.frame()
```


```{r}
for (i in 1:25) {
  x = (25*i) - 25
  url <- paste0("https://www.prosportstransactions.com/basketball/Search/SearchResults.php?Player=&Team=&BeginDate=2023-10-01&EndDate=2024-04-01&InjuriesChkBx=yes&Submit=Search&start=", x)
  webpage <- read_html(url)
  
  data_1 <- webpage %>%
  html_nodes("tr") %>%
  html_text()
  
  df <- data.frame(Column_1 = data_1)
  
  split_values <- strsplit(df$Column_1, "  ")


max_length <- max(sapply(split_values, length))

split_values <- lapply(split_values, function(x) c(x, rep(NA, max_length - length(x))))

df_split <- data.frame(do.call(rbind, split_values))


colnames(df_split) <- c("Date", "Team", "Acquired", "Relinquished", "Notes")

injuries <- rbind(injuries, df_split)



}

```

```{r}
injuries <- injuries[-1,] |> 
  select(1:5)

injuries$Date = str_replace_all(injuries$Date, "\r\n", "")
injuries$Team = str_replace_all(injuries$Team, "\r\n", "")
injuries$Acquired = str_replace_all(injuries$Acquired, "\r\n", "")
injuries$Relinquished = str_replace_all(injuries$Relinquished, "\r\n", "")
injuries$Notes = str_replace_all(injuries$Notes, "\r\n", "")


toDelete <- seq(27, 614, 27)

#Tried to clean, but not important right now


seq(27, 614, 27)

#injuries[-toDelete,][-toDelete,][-toDelete,]

#  injuries <- injuries[-toDelete,]
  
  #Putting this twice b/c two problematic rows  
 # injuries <- injuries[-toDelete,]


```




```{r}
combined <- combined |> 
  relocate(GAME_DATE) |> arrange(GAME_DATE)

combined$team_mins_per_game_injured <- NA


```


Source: https://www.nbastuffer.com/2023-2024-nba-player-stats/

```{r}
injuries |> 
  filter(Team == " Lakers")
```

Limitation: Clearly, does not take into account season-ending injuries if we only look at mins PG.

```{r}
combined <- combined |> 
  arrange(TEAM_NAME, GAME_DATE)

#write.csv(combined, "/Users/blakefuquay/Downloads/injuries.csv")


#I am counting on-day 


```

```{r}
library(readr)
combined <- read_csv("/Users/ethantur/Documents/injuries.csv")

combined
```

```{r}
# Load necessary libraries
library(dplyr)
library(readr)

# Load the dataset
game_stats <- combined

# Inspect the dataset
head(game_stats)

```

```{r}

# Calculate Team Shooting Percentage
game_stats <- game_stats %>%
  mutate(Shooting_Percentage = FGM / FGA) %>%
  group_by(TEAM_NAME) %>%
  mutate(Avg_Shooting_Percentage = mean(Shooting_Percentage, na.rm = TRUE))

# Calculate Average OREB per Game
game_stats <- game_stats %>%
  group_by(TEAM_NAME) %>%
  mutate(Avg_OREB = mean(OREB, na.rm = TRUE))

# Opposition Team's Historic DREB (this would require a bit more complex logic to calculate historically for each game)
game_stats <- game_stats %>%
  group_by(MATCHUP) %>%
  mutate(Opponent_Avg_DREB = mean(DREB, na.rm = TRUE))

game_stats
```

```{r}
# Splitting the data into training and testing sets 
set.seed(123)
training_indices <- sample(seq_len(nrow(game_stats)), size = floor(0.8 * nrow(game_stats)))
training_data <- game_stats[training_indices, ]
testing_data <- game_stats[-training_indices, ]

# Build the model
model <- lm(OREB ~ Avg_Shooting_Percentage + Avg_OREB + Opponent_Avg_DREB, data = training_data)

# Summary of the model
summary(model)

# Predict and evaluate
predictions <- predict(model, newdata = testing_data)
mae <- mean(abs(predictions - testing_data$OREB))
print(paste("Mean Absolute Error:", mae))

```


```{r}
game_stats <- game_stats %>%
  mutate(
    # Shooting Efficiency: Points per Field Goal Attempt and Free Throw Attempt
    SE = PTS / (FGA + 0.44 * FTA), # The 0.44 factor adjusts for and-one's, technical foul shots, and three-shot fouls
    
    # Defensive Pressure: Combining Steals and Blocks
    DP = (STL + BLK) / MIN, # Normalized by minutes played
    
    # Home Advantage as a binary variable
    Home = ifelse(grepl("vs", MATCHUP), 1, 0)
  )

# Prepare for modeling: Remove any rows with NAs created during feature engineering
#game_stats <- na.omit(game_stats)
game_stats$Pace = (game_stats$FGA + 0.44 * game_stats$FTA + game_stats$TOV + game_stats$OREB) / game_stats$MIN
# Estimate possessions based on available stats
game_stats$Possessions <- with(game_stats, 0.96 * (FGA + 0.44 * FTA - OREB + TOV))

# Calculate ORtg and DRtg
game_stats <- game_stats %>%
  mutate(ORtg = 100 * PTS / Possessions,
         DRtg = 100 * ifelse(Home == 1, visitor_pts, home_pts) / Possessions)

game_stats
```

```{r}
# Assuming 'home_prior_form' and 'visitor_prior_form' are encoded in a win-loss format (e.g., "WWL")
game_stats$HomeFormScore <- stringr::str_count(game_stats$home_prior_form, "W") - stringr::str_count(game_stats$home_prior_form, "L")
game_stats$VisitorFormScore <- stringr::str_count(game_stats$visitor_prior_form, "W") - stringr::str_count(game_stats$visitor_prior_form, "L")

game_stats$FormDiff <- game_stats$HomeFormScore - game_stats$VisitorFormScore
game_stats <- game_stats %>%
  select(-game_start_time, -home_prior_form, -visitor_prior_form)# %>%
  #na.omit()
game_stats

```



```{r}
predictions <- read.csv("/Users/ethantur/Downloads/predictions.csv")
predictions <- predictions |> 
  rename("Predicted OREB" = OREB, "Predicted Total" = Total, "Predicted Spread" = Spread)


```

```{r}

gamestats_4_6 <- read_csv("game_stats_4_6.csv")

```
```{r}
# Calculate Team Shooting Percentage
game_stats <- game_stats %>%
  mutate(Shooting_Percentage = FGM / FGA) %>%
  group_by(TEAM_NAME) %>%
  mutate(Avg_Shooting_Percentage = mean(Shooting_Percentage, na.rm = TRUE))

# Calculate Average OREB per Game
game_stats <- game_stats %>%
  group_by(TEAM_NAME) %>%
  mutate(Avg_OREB = mean(OREB, na.rm = TRUE))

# Opposition Team's Historic DREB (this would require a bit more complex logic to calculate historically for each game)
# For simplification, let's calculate the average DREB for the season
game_stats <- game_stats %>%
  group_by(MATCHUP) %>%
  mutate(Opponent_Avg_DREB = mean(DREB, na.rm = TRUE))

# Since calculating the tendencies of different players on teams might be too specific and complex for this example,
# we'll proceed with the above features for the model.
game_stats
```

```{r}
game_stats<- game_stats |> 
  select(-SEASON_ID, -TEAM_ID, -TEAM_ABBREVIATION, -GAME_ID, -game_id) |> 
  arrange(GAME_DATE)
```


```{r}
write.csv(game_stats, "game_stats_4_9.csv")
          

```


```{r}
game_stats |> 
  group_by(TEAM_NAME) |> 
  summarise(mean(Pace))
```
```{r}
game_stats$GAME_DATE <- as.Date(game_stats$GAME_DATE, format = "%Y-%m-%d")

game_stats$month <- months(game_stats$GAME_DATE)

march_april_data <- subset(game_stats, month %in% c("March", "April"))

for_pred <- march_april_data |> 
  summarise(Pace = mean(Pace), Possessions = mean(Possessions),DREB =  mean(DREB), OREB = mean(OREB), ORtg = mean(ORtg), DRtg = mean(DRtg), DP = mean(DP), SE = mean(SE), average_ast = mean(average_ast), average_treb = mean(average_treb), Avg_Shooting_Percentage = mean(Avg_Shooting_Percentage), FGA = mean(FGA), FTA = mean(FTA), FG3M = mean(FG3M), FGM = mean(FGM), FG_PCT = mean(FG_PCT))


```

```{r}
predictions <- read_csv("predictions.csv")

predictions <- predictions |> 
  select(1:5) |> 
  rename(Away = Away...1, Home = Home...2, OREB = OREB...5)


```
```{r}
for (i in nrow(predictions)) {
  Spread[i] = ...
}
```

```{r}
for_pred
```


```{r}

for (i in 1:57) {
  for (j in 1:nrow(for_pred)) {
    if(for_pred[j,]$TEAM_NAME == predictions[i,]$Away){
        predictions[i,]$Total <- -189.1534 + 3.3662*for_pred[j,]$Pace + 2.559*for_pred[j,]$Possessions - 0.3488*for_pred[j,]$FGA - 0.2114*for_pred[j,]$FTA + 0.0773*for_pred[j,]$FG3M - 0.3813*for_pred[j,]$FGM + 0.8862*for_pred[j,]$ORtg + 0.9662*for_pred[j,]$DRtg + .0031*for_pred[j,]$FGA*for_pred[j,]$FTA + .0063*for_pred[j,]$FGA*for_pred[j,]$FGM
        
    }
  }

}




for (i in 1:57) {
  for (j in 1:nrow(for_pred)) {
    if(for_pred[j,]$TEAM_NAME == predictions[i,]$Home){
        predictions[i,]$Total <- 
          (predictions[i,]$Total +
        
        (-189.1534 + 3.3662*for_pred[j,]$Pace + 2.559*for_pred[j,]$Possessions - 0.3488*for_pred[j,]$FGA - 0.2114*for_pred[j,]$FTA + 0.0773*for_pred[j,]$FG3M - 0.3813*for_pred[j,]$FGM + 0.8862*for_pred[j,]$ORtg + 0.9662*for_pred[j,]$DRtg + .0031*for_pred[j,]$FGA*for_pred[j,]$FTA + .0063*for_pred[j,]$FGA*for_pred[j,]$FGM))/2
        
    }
  }

}



```


```{r}
for (i in 1:57) {
  for (j in 1:nrow(for_pred)) {
    if(for_pred[j,]$TEAM_NAME == predictions[i,]$Away){
        predictions[i,]$OREB <- 6.3655 + 0.2168*sqrt(for_pred[j,]$DREB) + 0.065*for_pred[j,]$average_treb - 0.4194*for_pred[j,]$Possessions - 6.0219*for_pred[j,]$Avg_Shooting_Percentage - 0.5204*for_pred[j,]$FTA + 103.7938*for_pred[j,]$FG_PCT - 2.4527*for_pred[j,]$FGM + 93.064*for_pred[j,]$Pace - .0363*for_pred[j,]$FGA + .0065*for_pred[j,]$FTA*for_pred[j,]$FGA + .014*for_pred[j,]$FGM*for_pred[j,]$FGA
        
    }
  }

}


for (i in 1:57) {
  for (j in 1:nrow(for_pred)) {
    if(for_pred[j,]$TEAM_NAME == predictions[i,]$Home){
        predictions[i,]$OREB <- (predictions[i,]$OREB + 6.3655 + 0.2168*sqrt(for_pred[j,]$DREB) + 0.065*for_pred[j,]$average_treb - 0.4194*for_pred[j,]$Possessions - 6.0219*for_pred[j,]$Avg_Shooting_Percentage - 0.5204*for_pred[j,]$FTA + 103.7938*for_pred[j,]$FG_PCT - 2.4527*for_pred[j,]$FGM + 93.064*for_pred[j,]$Pace - .0363*for_pred[j,]$FGA + .0065*for_pred[j,]$FTA*for_pred[j,]$FGA + .014*for_pred[j,]$FGM*for_pred[j,]$FGA)
        
    }
  }

}
```


